# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6578743d04c627f84b0690c6dbdb035ee996cfb50d3cf0531dc85eb140e8d77a5e5418cf81a53f159b38dfdc7928a92404e2e3c4db7638a527955f467330c786

test:
  secret_key_base: bdea626b33b7a7bd2c6c6e797fd84d38ff8dc77fd753e447d938483e6c4d53f4082cbf05cacaf09fa1675e105d59c51ca4535d10e72ae15e68c379f6a80ed46a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
